[ru] cs-221-logic-models
shervinea/cheatsheet-translation pull request #217
Opened 2020-12-23 09:05 UTC by AlexandrParkhomenko

2021-02-16 19:25 UTC, geotrush requested changes
Perfect! I've provided some fixes.

2021-02-16 19:25 UTC, geotrush commented on ru/cs-221-logic-models.md
> +&#10230; [Утверждение, Отрицание, Конъюнкция, Дизъюнкция, Импликация, Biconditional (Эквивалентность)]
```suggestion
&#10230; [Утверждение, Отрицание, Конъюнкция, Дизъюнкция, Импликация, Эквивалентность]
```

2021-02-16 19:25 UTC, geotrush commented on ru/cs-221-logic-models.md
> +&#10230; [not f, f and g, f or g, if f then g, f, that is to say g]
```suggestion
&#10230; [не f, f и g, f или g, если f то g, f означает g]
```

2021-02-16 19:25 UTC, geotrush commented on ru/cs-221-logic-models.md
> +&#10230; Модель ― Модель w обозначает присвоение двоичных весов символам высказываний (пропозициональным).
```suggestion
&#10230; Модель ― Модель w обозначает присвоение бинарных весов символам высказываний.
```

2021-02-16 19:25 UTC, geotrush commented on ru/cs-221-logic-models.md
> +&#10230; [Вывод на основе разрешения ― Алгоритм вывода на основе разрешении. Включает следующие шаги:, Шаг 1: Преобразовать все формулы в CNF, Шаг 2. Повторно применить правило разрешения, Шаг 3: Вер
```suggestion
&#10230; [Вывод на основе разрешения ― Алгоритм вывода на основе разрешения. Включает следующие шаги:, Шаг 1: Преобразовать все формулы в CNF, Шаг 2. Повторно применить правило разрешения, Шаг 3: Вернуть неудовлетворительно, если и только если выводится False]
```

2021-02-16 19:25 UTC, geotrush commented on ru/cs-221-logic-models.md
> +&#10230; Подстановка ― Замена θ отображает переменные в термы, а Subst[θ,f] обозначает результат замены θ на f.
```suggestion
&#10230; Подстановка ― Замена θ отображает переменные в составляющие формул, а Subst[θ,f] обозначает результат замены θ на f.
```

2021-02-16 19:25 UTC, geotrush commented on ru/cs-221-logic-models.md
> +&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/shervinea
```suggestion
&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/afshinea и https://github.com/shervinea
```

2021-02-16 19:25 UTC, geotrush commented on ru/cs-221-logic-models.md
> +&#10230; Российская адаптация: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```suggestion
&#10230; Переведено на русский язык: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```

2021-02-16 19:25 UTC, geotrush commented on ru/cs-221-logic-models.md
> +&#10230; Проверено X, Y и Z
```suggestion
&#10230; Проверено на русском языке: Труш Георгий (Georgy Trush) ― https://github.com/geotrush
```

2021-02-16 19:25 UTC, geotrush commented on ru/cs-221-logic-models.md
> +&#10230; Шпаргалки по искусственному интеллекту теперь доступны в формате [target language].
```suggestion
&#10230; Шпаргалки по искусственному интеллекту теперь доступны на русском языке.
```

2021-02-17 16:23 UTC, AlexandrParkhomenko commented on ru/cs-221-logic-models.md
> +&#10230; [Вывод на основе разрешения ― Алгоритм вывода на основе разрешении. Включает следующие шаги:, Шаг 1: Преобразовать все формулы в CNF, Шаг 2. Повторно применить правило разрешения, Шаг 3: Вер
Да! Уберём запятую. Никто не обещал простоты пасинга массивов. Я специально программу писал для проверки длины таких массивов. Для вас могу что угодно в веб версии поравить.

2021-02-17 16:26 UTC, AlexandrParkhomenko commented on ru/cs-221-logic-models.md
> +&#10230; [not f, f and g, f or g, if f then g, f, that is to say g]
это надписи на картинках

2021-02-17 16:31 UTC, AlexandrParkhomenko commented on ru/cs-221-logic-models.md
> +&#10230; Модели логик с логикой высказываний и логикой первого порядка
Похоже, что здесь описаны различные логики.

2022-08-18 17:52 UTC, closed without merging