[ru] cs-221-reflex-models
shervinea/cheatsheet-translation pull request #218
Opened 2020-12-23 09:16 UTC by AlexandrParkhomenko

2021-02-16 10:44 UTC, geotrush requested changes
Another great Russian translation! I'm proposing only some small improvements.

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Модели на основе рефлексов с машинным обучением
```suggestion
&#10230; Модели машинного обучения на основе рефлексов
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; В этом разделе мы рассмотрим модели, основанные на рефлексах, которые можно улучшить с опытом, просмотрев образцы с парами вход-выход.
```suggestion
&#10230; В этом разделе мы рассмотрим модели, основанные на рефлексах, которые улучшаются по мере накопления опыта, обучаясь на парах наблюдений вход-выход.
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Оценка ― Оценка s(x,w) примера (ϕ(x),y) ∈Rd×R, связанного с линейной моделью весов w∈Rd, дается внутренним произведением:
```suggestion
&#10230; Оценка ― Оценка s(x,w) примера (ϕ(x),y) ∈Rd×R, связанного с линейной моделью весов w∈Rd, задается скалярным произведением:
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Линейный классификатор ― Для вектора весов w∈Rd и вектора признаков ϕ(x)∈Rd двоичный линейный классификатор fw имеет вид:
```suggestion
&#10230; Линейный классификатор ― Для вектора весов w∈Rd и вектора признаков ϕ(x)∈Rd бинарный линейный классификатор fw имеет вид:
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Отступ ― Отступ m(x,y,w)∈R примера (ϕ(x),y)∈Rd×{−1,+1}, связанная с линейной моделью весов w∈Rd, количественно оценивает уверенность прогноз: большие значения лучше. Задается:
```suggestion
&#10230; Зазор ― Зазор m(x,y,w)∈R примера (ϕ(x),y)∈Rd×{−1,+1}, связанная с линейной моделью весов w∈Rd, количественно оценивает уверенность прогноза: большие значения лучше. Задается следующим образом:
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Разность ― Разность res(x,y,w)∈R определяется как величина, на которую прогноз fw(x) превышает целевой y:
```suggestion
&#10230; Остаток ― Остаток res(x,y,w)∈R определяется как величина, на которую прогноз fw(x) превышает целевой y:
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Функция потерь ― Функция потерь Loss(x,y,w) количественно определяет, насколько мы недовольны весами w модели в задаче прогнозирования выхода y из входа x. Это количество, которое мы хотим м
```suggestion
&#10230; Функция потерь ― Функция потерь Loss(x,y,w) количественно определяет, насколько мы недовольны весами w модели в задаче прогнозирования выхода y на основе входа x. Это количество, которое мы хотим минимизировать во время процесса обучения.
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Классификационный случай ― Классификация выборки x истинной метки y∈{−1,+1} с линейной моделью весов w может быть выполнена с помощью предиктора fw(x)≜sign(s(x,w)). В этой ситуации интересую
```suggestion
&#10230; Случай классификации ― Классификация выборки x истинной метки y∈{−1,+1} с линейной моделью весов w может быть выполнена с помощью предиктора fw(x)≜sign(s(x,w)). В этой ситуации интересующий показатель, определяющий качество классификации, задается зазором m(x,y,w) и может использоваться со следующими функциями потерь:
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; [Название, Иллюстрация, потеря ноль единицы, потеря петли, логистическая потеря]
```suggestion
&#10230; [Название, Иллюстрация, Zero-one loss, Hinge loss, Logistic loss]
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Случай регрессии ― Предсказание выборки x истинной метки y∈R с помощью линейной модели весов w может быть выполнено с помощью предиктора fw(x)≜s(x,w). В этой ситуации интересующий показатель
```suggestion
&#10230; Случай регрессии ― Предсказание выборки x истинной метки y∈R с помощью линейной модели весов w может быть выполнено с помощью предиктора fw(x)≜s(x,w). В этой ситуации интересующий показатель, количественно оценивающий качество регрессии, задается зазором res(x,y,w) и может использоваться со следующими функциями потерь:
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; [Название, Квадратичная потеря, Абсолютное отклонение, Иллюстрация]
```suggestion
&#10230; [Название, Squared loss, Absolute deviation loss, Иллюстрация]
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; k-ближайшие соседи ― Алгоритм k-ближайших соседей, широко известный как k-NN, представляет собой непараметрический подход, в котором ответ для точки данных определяется характером её k сосед
```suggestion
&#10230; k-ближайших соседей ― Алгоритм k-ближайших соседей, широко известный как k-NN, представляет собой непараметрический подход, в котором метка новой точки данных определяется признаками её k соседей из обучающего набора. Его можно использовать в случаях как классификации, так и регрессии.
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Стохастические обновления ― Stochastic gradient descent (SGD) обновляет параметры модели по одному обучающему примеру (ϕ(x),y)∈Dtrain за раз. Этот метод приводит к иногда шумным, но быстрым
```suggestion
&#10230; Стохастические обновления ― Stochastic gradient descent (SGD) обновляет параметры модели по одному обучающему примеру (ϕ(x),y)∈Dtrain за раз. Этот метод зачастую приводит к шумным, но быстрым обновлениям.
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Доводка моделей
```suggestion
&#10230; Дообучение моделей
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Обратное распространение ― Backpropagation - Прямой проход выполняется через fi, которое является значением подвыражения с индексом i, а обратный проход выполняется через gi=∂out∂fi и предст
```suggestion
&#10230; Обратное распространение ошибки ― Backpropagation - Прямой проход сети выполняется через fi, которое является значением подвыражения с индексом i, а обратный проход выполняется через gi=∂out∂fi и отражает то, как сильно fi влияет на выход.
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Ошибка аппроксимации и оценки ― Ошибка аппроксимации ϵapprox представляет, как далеко весь класс гипотез F от целевого предиктора g∗, в то время как ошибка оценки ϵest количественно определя
```suggestion
&#10230; Ошибки приближения и оценки ― Ошибка приближения ϵapprox отражает то, насколько далеко весь класс гипотез F от целевого предиктора g∗, в то время как ошибка оценки ϵest количественно определяет, насколько хорош предиктор ^f по отношению к лучшему предиктору f∗ из класса гипотез F.
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Гиперпараметры ― это свойства алгоритма обучения и включают функции, параметр регуляризации λ, количество итераций T, размер шага η и так далее.
```suggestion
&#10230; Гиперпараметры ― это свойства алгоритма обучения, включающие параметр регуляризации λ, количество итераций T, размер шага η и так далее.
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Кластеризация ― Дан обучающий набор входных точек Dtrain, цель алгоритма кластеризации состоит в том, чтобы назначить каждую точку ϕ(xi) кластеру zi∈{1,...,k}
```suggestion
&#10230; Кластеризация ― Дан обучающий набор входных точек Dtrain, цель алгоритма кластеризации состоит в том, чтобы определить каждую точку ϕ(xi) к одному из кластеров zi∈{1,...,k}
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; [Линейные предикторы, Вектор признаков, Линейный классификатор/регрессия, Отступn]
```suggestion
&#10230; [Линейные предикторы, Вектор признаков, Линейный классификатор/регрессия, Зазор]
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; [Нелинейные предикторы, k-ближайшие соседи, Нейронные сети]
```suggestion
&#10230; [Нелинейные предикторы, k-ближайших соседей, Нейронные сети]
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; [Модели тонкой настройки, Класс гипотез, Обратное распространение, Регуляризация, Наборы словарей]
```suggestion
&#10230; [Модели дообучения, Класс гипотез, Обратное распространение ошибки, Регуляризация, Наборы словарей]
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/shervinea
```suggestion
&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/afshinea и https://github.com/shervinea
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Российская адаптация: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```suggestion
&#10230; Переведено на русский язык: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```

2021-02-16 10:44 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Проверено X, Y и Z
```suggestion
&#10230; Проверено на русском языке: Труш Георгий (Georgy Trush) ― https://github.com/geotrush
```

2021-02-16 17:12 UTC, AlexandrParkhomenko commented on ru/cs-221-reflex-models.md
> +&#10230; Функция потерь ― Функция потерь Loss(x,y,w) количественно определяет, насколько мы недовольны весами w модели в задаче прогнозирования выхода y из входа x. Это количество, которое мы хотим м
В веб-версии добавил "по известному входу" и training оставил,  train-validation-test

2021-02-16 17:23 UTC, AlexandrParkhomenko commented on ru/cs-221-reflex-models.md
> +&#10230; Гиперпараметры ― это свойства алгоритма обучения и включают функции, параметр регуляризации λ, количество итераций T, размер шага η и так далее.
Гиперпараметры-функции как результаты сетей?

2021-02-16 17:26 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Гиперпараметры ― это свойства алгоритма обучения и включают функции, параметр регуляризации λ, количество итераций T, размер шага η и так далее.
@AlexandrParkhomenko Входы, выходы и промежуточные состояния сетей не являются гиперпараметрами.

2021-02-16 17:27 UTC, AlexandrParkhomenko commented on ru/cs-221-reflex-models.md
> +&#10230; Проверено X, Y и Z
Спасибо, материал теперь лучше.

--------------------------------------------------------------

Thank you, cheats are better now.

2021-02-17 15:08 UTC, geotrush requested changes
Edited the last line with appropriate language.

2021-02-17 15:08 UTC, geotrush commented on ru/cs-221-reflex-models.md
> +&#10230; Шпаргалки по искусственному интеллекту теперь доступны в формате [target language].
```suggestion
&#10230; Шпаргалки по искусственному интеллекту теперь доступны на русском языке.
```

2022-08-18 17:52 UTC, closed without merging