[ru] cs-221-states-models
shervinea/cheatsheet-translation pull request #219
Opened 2020-12-23 09:36 UTC by AlexandrParkhomenko

2021-02-16 12:18 UTC, geotrush requested changes
Amazing translation! Only some minor changes are necessary.

2021-02-16 12:18 UTC, geotrush commented on ru/cs-221-states-models.md
> +&#10230; Примечание: предположим, что полезность агента противоположна полезности оппонента.
```suggestion
&#10230; Примечание: предположим, что полезность агента имеет противоположенный знак по сравнению с полезностью оппонента.
```

2021-02-16 12:18 UTC, geotrush commented on ru/cs-221-states-models.md
> +&#10230; [Типы политик ― Есть два типа политик:, Детерминистские политики, обозначаются πp(s), действия игрока p в состоянии s., Стохастические политики, обозначаются πp(s,a)∈[0,1], вероятности совер
```suggestion
&#10230; [Типы политик ― Есть два типа политик:, Детерминистские политики, обозначаются πp(s), действия игрока p в состоянии s., Стохастические политики, обозначаются πp(s,a)∈[0,1], являющиеся вероятностями совершения игроком p действия a в состоянии s.]
```

2021-02-16 12:18 UTC, geotrush commented on ru/cs-221-states-models.md
> +&#10230; Альфа-бета обрезка ― Alpha-beta pruning - это общий для предметной области точный метод, оптимизирующий алгоритм минимакса, избегая ненужного исследования частей игрового дерева. Для этого к
```suggestion
&#10230; Альфа-бета обрезка ― Alpha-beta pruning - это общий для предметной области точный метод, оптимизирующий алгоритм минимакса, избегая ненужного исследования частей игрового дерева. Для этого каждый игрок отслеживает наилучшее значение, на которое он может надеяться (сохраняется в α для максимизирующего игрока и в β для минимизирующего игрока). На данном шаге условие β<α означает, что оптимальный путь не будет в текущей ветви, поскольку у игрока на предыдущем шаге имелся более хороший вариант.
```

2021-02-16 12:18 UTC, geotrush commented on ru/cs-221-states-models.md
> +&#10230; [A со звездой поиск, Эвристическая функция, Алгоритм, Консистентность, Корректность, Допустимость, Эффективность]
```suggestion
&#10230; [Алгоритм поиска A*, Эвристическая функция, Алгоритм, Консистентность, Корректность, Допустимость, Эффективность]
```

2021-02-16 12:18 UTC, geotrush commented on ru/cs-221-states-models.md
> +&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/shervinea
```suggestion
&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/afshinea и https://github.com/shervinea
```

2021-02-16 12:18 UTC, geotrush commented on ru/cs-221-states-models.md
> +&#10230; Российская адаптация: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```suggestion
&#10230; Переведено на русский язык: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```

2021-02-16 12:18 UTC, geotrush commented on ru/cs-221-states-models.md
> +&#10230; Проверено X, Y и Z
```suggestion
&#10230; Проверено на русском языке: Труш Георгий (Georgy Trush) ― https://github.com/geotrush
```

2021-02-16 12:18 UTC, geotrush commented on ru/cs-221-states-models.md
> +&#10230; Шпаргалки по искусственному интеллекту теперь доступны в формате [target language].
```suggestion
&#10230; Шпаргалки по искусственному интеллекту теперь доступны на русском языке.
```

2021-02-16 12:45 UTC, AlexandrParkhomenko commented on ru/cs-221-states-models.md
> +&#10230; [Самопереход, Много родителей, Цикл, Много корней, Правильное дерево]
Authors need to generate images. I don't know what patterns.

2021-02-16 12:52 UTC, geotrush commented on ru/cs-221-states-models.md
> +&#10230; [Самопереход, Много родителей, Цикл, Много корней, Правильное дерево]
What do you mean? Here authors list basic types of graph patterns that are not present in trees, then they end the list with the ordinary tree structure. It is clear from images in the pdf.

2021-02-16 12:56 UTC, AlexandrParkhomenko commented on ru/cs-221-states-models.md
> +&#10230; [Компромисс при выборе эвристики ― При выборе эвристики необходимо уравновесить два аспекта:, Вычислительная эффективность: h(s)=FutureCostrel(s) должно быть легко вычислить. Она должна созд
I put a comma on the web.

2021-02-16 13:00 UTC, geotrush commented on ru/cs-221-states-models.md
> +&#10230; [Компромисс при выборе эвристики ― При выборе эвристики необходимо уравновесить два аспекта:, Вычислительная эффективность: h(s)=FutureCostrel(s) должно быть легко вычислить. Она должна созд
Right, I've corrected it to a comma. Wasn't sure if commas are available to use since there was a semicolon.

2021-02-16 13:04 UTC, AlexandrParkhomenko commented on ru/cs-221-states-models.md
> +&#10230; State-action-reward-state-action (SARSA) ― Состояние-действие-награда-состояние-действие - это оценка Qπ метода начальной загрузки с использованием как необработанных данных, так и оценок ка
бутстрэп

2021-02-16 13:08 UTC, geotrush commented on ru/cs-221-states-models.md
> +&#10230; State-action-reward-state-action (SARSA) ― Состояние-действие-награда-состояние-действие - это оценка Qπ метода начальной загрузки с использованием как необработанных данных, так и оценок ка
https://ru.wikipedia.org/wiki/Бутстрэп_(статистика)

2021-02-16 13:10 UTC, geotrush commented on ru/cs-221-states-models.md
> +&#10230; [Самопереход, Много родителей, Цикл, Много корней, Правильное дерево]
> Authors need to generate images. I don't know what patterns.
What do you mean? Here authors list basic types of graph patterns that are not present in trees, then they end the list with the correct tree structure. It is clear from images in the pdf.

2021-02-16 19:25 UTC, AlexandrParkhomenko commented on ru/cs-221-states-models.md
> +&#10230; [Самопереход, Много родителей, Цикл, Много корней, Правильное дерево]
This is image, not text.
![](https://alexandrparkhomenko.github.io/stanford/cs-221/states-models/tree.png?2d18a75bbffc54c7db56dd83aed1e224)

2021-02-17 15:10 UTC, geotrush requested changes
Edited the last line with appropriate language.

2021-02-17 15:10 UTC, geotrush commented on ru/cs-221-states-models.md
> +&#10230; Шпаргалки по искусственному интеллекту теперь доступны в формате [target language].
```suggestion
&#10230; Шпаргалки по искусственному интеллекту теперь доступны на русском языке.
```

2022-08-18 17:52 UTC, closed without merging