[ru] cs-229-deep-learning
shervinea/cheatsheet-translation pull request #221
Opened 2020-12-23 10:26 UTC by AlexandrParkhomenko

2021-02-15 19:27 UTC, geotrush requested changes
Very good! I'm proposing some minor changes.

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Отметив i-й слой сети и j-ю скрытую единицу слоя, мы имеем:
```suggestion
&#10230; Отметив i-ый слой сети и j-ый нейрон скрытого слоя, мы имеем:
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Функция активации ― используются в конце скрытого блока, чтобы внести в модель нелинейность. Вот самые распространенные:
```suggestion
&#10230; Функция активации ― используется на выходе каждого нейрона скрытого слоя, чтобы внести в модель нелинейность. Вот самые распространенные:
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; [Сигмоида, Tanh, ReLU, ReLU с утечкой]
```suggestion
&#10230; [Sigmoid, Tanh, ReLU, Leaky ReLU]
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Функция потерь на основе перекрестной энтропии ― в контексте нейронных сетей обычно используются потери кросс-энтропии L(z,y), которые определяются следующим образом:
```suggestion
&#10230; Функция потерь на основе перекрестной энтропии ― в контексте нейронных сетей обычно используется функция потерь кросс-энтропии L(z,y), которая определяется следующим образом:
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Обратное распространение ― это метод обновления весов в нейронной сети с учетом фактического и желаемого результата. Производная по весу w вычисляется с использованием цепного правила и имее
```suggestion
&#10230; Обратное распространение ошибки ― это метод обновления весов в нейронной сети с учетом фактических выходов сети и желаемых меток классов. Производная по весу w вычисляется с использованием цепного правила и имеет следующий вид:
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Шаг 2: Выполнить прямое распространение и получить соответствующие значения функции стоимости.
```suggestion
&#10230; Шаг 2: Выполнить прямой проход сети для получения соответствующих значений функции стоимости.
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Шаг 1. Возьмите пакет обучающих данных.
```suggestion
&#10230; Шаг 1. Взять пакет обучающих данных.
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Шаг 3: Выполнить обратное распространение ошибки и получить градиенты.
```suggestion
&#10230; Шаг 3: Выполнить обратное распространение ошибки для получения градиентов.
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Шаг 4. Использовать градиенты и обновить веса сети.
```suggestion
&#10230; Шаг 4. Использовать градиенты, чтобы обновить веса сети.
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Прореживание (Dropout) ― это метод, предназначенный для предотвращения переобучения на обучающих данных путем исключения блоков в нейронной сети. На практике нейроны либо отбрасываются с вер
```suggestion
&#10230; Прореживание (Dropout) ― это метод, предназначенный для предотвращения переобучения путем удаления нейронов из сети. На практике нейроны либо отбрасываются с вероятностью p, либо сохраняются с вероятностью 1−p
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Обычно это делается после полносвязного / сверточного слоя и до функции нелинейности и направлено на повышение скорости обучения и уменьшение сильной зависимости от инициализации.
```suggestion
&#10230; Обычно это делается после полносвязного/сверточного слоя и до функции нелинейности и направлено на повышение скорости обучения и уменьшение сильной зависимости от инициализации.
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Уравнение Беллмана - Оптимальные уравнения Беллмана характеризуют функцию цены Vπ∗ оптимальной политики π∗:
```suggestion
&#10230; Уравнение Беллмана - Оптимальные уравнения Беллмана характеризуют функцию ценности Vπ∗ оптимальной политики π∗:
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; раз предприняли действие a в состоянии s и добрались до s′
```suggestion
&#10230; раз предприняли действие a в состоянии s и перешли в s′
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; [Нейронные Сети, Архитектура, Функция активации, Обратное распространение, Прореживание]
```suggestion
&#10230; [Нейронные Сети, Архитектура, Функция активации, Обратное распространение ошибки, Прореживание]
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/shervinea
```suggestion
&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/afshinea и https://github.com/shervinea
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Российская адаптация: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```suggestion
&#10230; Переведено на русский язык: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```

2021-02-15 19:27 UTC, geotrush commented on ru/cs-229-deep-learning.md
> +&#10230; Проверено X, Y и Z
```suggestion
&#10230; Проверено на русском языке: Труш Георгий (Georgy Trush) ― https://github.com/geotrush
```

2021-02-16 16:14 UTC, AlexandrParkhomenko commented on ru/cs-229-deep-learning.md
> +&#10230; Функция активации ― используются в конце скрытого блока, чтобы внести в модель нелинейность. Вот самые распространенные:
Упс. Тут неправы авторы.

2021-02-16 16:24 UTC, AlexandrParkhomenko commented on ru/cs-229-deep-learning.md
> +&#10230; Прореживание (Dropout) ― это метод, предназначенный для предотвращения переобучения на обучающих данных путем исключения блоков в нейронной сети. На практике нейроны либо отбрасываются с вер
Неееет не удаляем, отключаем.

2021-02-16 16:26 UTC, AlexandrParkhomenko commented on ru/cs-229-deep-learning.md
> +&#10230; Обычно это делается после полносвязного / сверточного слоя и до функции нелинейности и направлено на повышение скорости обучения и уменьшение сильной зависимости от инициализации.
"или" хорошо подойдёт?

2021-02-16 16:35 UTC, AlexandrParkhomenko commented on ru/cs-229-deep-learning.md
> +&#10230; раз предприняли действие a в состоянии s и добрались до s′
нет в окончательном тексте

2022-08-18 17:52 UTC, closed without merging