[ru] cs-229-linear-algebra
shervinea/cheatsheet-translation pull request #222
Opened 2020-12-23 10:37 UTC by AlexandrParkhomenko

2021-02-17 15:04 UTC, geotrush requested changes
Great! I've fixed some mistakes.

2021-02-17 15:04 UTC, geotrush commented on ru/cs-229-linear-algebra.md
> +&#10230; Сингулярное разложение ― Для данной матрицы A размеров m×n разложение по сингулярным числам (singular-value decomposition, SVD) представляет собой метод факторизации, который гарантирует сущ
```suggestion
&#10230; Сингулярное разложение ― Для данной матрицы A размеров m×n разложение по сингулярным числам (singular-value decomposition, SVD) представляет собой метод факторизации, который гарантирует существование следующих матриц: унитарной U m×m, диагональной Σ m×n и унитарной V n×n, таких что:
```

2021-02-17 15:04 UTC, geotrush commented on ru/cs-229-linear-algebra.md
> +&#10230; Матричное исчисление
```suggestion
&#10230; Матричное дифференцирование
```

2021-02-17 15:04 UTC, geotrush commented on ru/cs-229-linear-algebra.md
> +&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/shervinea
```suggestion
&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/afshinea и https://github.com/shervinea
```

2021-02-17 15:04 UTC, geotrush commented on ru/cs-229-linear-algebra.md
> +&#10230; Российская адаптация: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```suggestion
&#10230; Переведено на русский язык: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```

2021-02-17 15:04 UTC, geotrush commented on ru/cs-229-linear-algebra.md
> +&#10230; Проверено X, Y и Z
```suggestion
&#10230; Проверено на русском языке: Труш Георгий (Georgy Trush) ― https://github.com/geotrush
```

2021-02-17 18:10 UTC, AlexandrParkhomenko commented on ru/cs-229-linear-algebra.md
> +&#10230; Матрица ― Мы обозначаем A∈Rm×n матрица с m строками и n столбцами, где Ai,j∈R - запись, расположенная в i-й строке и j-м столбце:
элемент, расположенный

2021-02-19 10:32 UTC, geotrush commented on ru/cs-229-linear-algebra.md
> +&#10230; Матрица ― Мы обозначаем A∈Rm×n матрица с m строками и n столбцами, где Ai,j∈R - запись, расположенная в i-й строке и j-м столбце:
@AlexandrParkhomenko Right, I've fixed it.

2022-08-18 17:52 UTC, closed without merging