[ru] cs-229-machine-learning-tips-and-tricks
shervinea/cheatsheet-translation pull request #223
Opened 2020-12-23 10:42 UTC by AlexandrParkhomenko

2021-02-15 19:51 UTC, geotrush requested changes
Great! I've reviewed the whole translation and suggested some minor changes.

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; В контексте бинарной классификации вот основные метрики, которые важно отслеживать, чтобы оценить производительность модели.
```suggestion
&#10230; В контексте бинарной классификации вот основные метрики, которые важно отслеживать, чтобы оценить качество модели.
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; Матрица ошибок ― Матрица ошибок используется для получения более полной картины при оценке производительности модели. Она определяется следующим образом:
```suggestion
&#10230; Матрица ошибок ― Матрица ошибок используется для получения более полной картины при оценке качества модели. Она определяется следующим образом:
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; [Прогнозируемый класс, Актуальный класс]
```suggestion
&#10230; [Прогнозируемый класс, Фактический класс]
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; Специфика выделенных отрицательных образцов
```suggestion
&#10230; Спецификация показывает, какая часть отрицательных наблюдений была выделена классификатором
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; Полнота показывает, какая часть положительных образцов была выделена классификатором
```suggestion
&#10230; Полнота показывает, какая часть положительных наблюдений была выделена классификатором
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; Receiver Operating (characteristic) Curve (ROC) ― Кривая рабочей характеристики приемника, также обозначенная как ROC, представляет собой график зависимости TPR от FPR при изменении порога.
```suggestion
&#10230; Receiver Operating Curve ― Кривая рабочей характеристики приемника, также обозначаемая как ROC, представляет собой график зависимости TPR от FPR при изменении порога. Эти показатели приведены в таблице ниже:
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; Базовые метрики ― Дана регрессионная модель f, для оценки производительности модели обычно используются следующие метрики:
```suggestion
&#10230; Базовые метрики ― Дана регрессионная модель f, для оценки качества модели обычно используются следующие метрики:
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; [Cумма квадратов общая (total), Сумма квадратов объясненная (regression), Сумма квадратов разностей (residual)]
```suggestion
&#10230; [Общая сумма квадратов, Объясненная сумма квадратов, Сумма квадратов остатков]
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; Регуляризация ― Процедура регуляризации направлена на то, чтобы модель не переобучалась на данных, и, таким образом, решает проблемы с высокой дисперсией. В следующей таблице суммированы раз
```suggestion
&#10230; Регуляризация ― Процедура регуляризации направлена на то, чтобы модель не переобучалась на данных, и, таким образом, решает проблемы, связанные с высокой дисперсией. В следующей таблице суммированы различные типы широко используемых методов регуляризации:
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; [Усложнить модель, Добавить больше параметров, Тренироваться дольше, Выполнить регуляризацию, Взять больше данных]
```suggestion
&#10230; [Усложнить модель, Добавить больше параметров, Тренировать дольше, Выполнить регуляризацию, Собрать больше данных]
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; Анализ ошибок ― Анализ ошибок - это анализ основной причины разницы в производительности между текущей и идеальной моделями.
```suggestion
&#10230; Анализ ошибок ― Анализ ошибок - это анализ основной причины разницы в качестве предсказаний между текущей и идеальной моделями.
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; Абляционный анализ ― Абляционный анализ анализирует первопричину разницы в производительности между текущей и базовой моделями.
```suggestion
&#10230; Абляционный анализ ― Абляционный анализ анализирует первопричину разницы в качестве предсказаний между текущей и базовой моделями.
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/shervinea
```suggestion
&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/afshinea и https://github.com/shervinea
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; Российская адаптация: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```suggestion
&#10230; Переведено на русский язык: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```

2021-02-15 19:51 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; Проверено X, Y и Z
```suggestion
&#10230; Проверено на русском языке: Труш Георгий (Georgy Trush) ― https://github.com/geotrush
```

2021-02-16 16:48 UTC, AlexandrParkhomenko commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; [Cумма квадратов общая (total), Сумма квадратов объясненная (regression), Сумма квадратов разностей (residual)]
Остатков чего?

2021-02-16 16:52 UTC, geotrush commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; [Cумма квадратов общая (total), Сумма квадратов объясненная (regression), Сумма квадратов разностей (residual)]
Остатков регрессии. Вы перед переводом с материалом ознакамливались? https://ru.wikipedia.org/wiki/Метод_наименьших_квадратов

2021-02-17 18:36 UTC, AlexandrParkhomenko commented on ru/cs-229-machine-learning-tips-and-tricks.md
> +&#10230; [Cумма квадратов общая (total), Сумма квадратов объясненная (regression), Сумма квадратов разностей (residual)]
Мне нравится мнемоника res-раз. В тексте идут формулы с сокращениями, проще будет когда показано, что сокращается.

2022-08-18 17:52 UTC, closed without merging