[ru] cs-229-probability
shervinea/cheatsheet-translation pull request #224
Opened 2020-12-23 10:50 UTC by AlexandrParkhomenko

2021-02-17 15:30 UTC, geotrush requested changes
Top-notch translation! And it seems to be the last one that needs reviewing.

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Памятка: Вероятности и Статистики
```suggestion
&#10230; Памятка: Теория Вероятности и Статистика
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Введение в вероятность и комбинаторику
```suggestion
&#10230; Введение в Теорию Вероятности и Комбинаторику
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Перестановка ― Permutation - это расположение r объектов из пула n объектов в заданном порядке. Количество таких расположений определяется как P(n,r), определяемое как:
```suggestion
&#10230; Перестановка ― Permutation - это расположение r объектов из набора n объектов в заданном порядке. Количество таких расположений определяется как P(n,r), определяемое как:
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Комбинация ― Combination - это расположение r объектов из пула, состоящего из n объектов, где порядок не имеет значения. Количество таких расположений дается C(n,r), определяемым как:
```suggestion
&#10230; Комбинация ― Combination - это расположение r объектов из набора, состоящего из n объектов, где порядок не имеет значения. Количество таких расположений задается C(n,r), определяемым как:
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Случайная величина ― случайная величина, которую часто называют X, представляет собой функцию, которая отображает каждый элемент в пространстве выборки на действительную линию.
```suggestion
&#10230; Случайная величина ― случайная величина, которую часто называют X, представляет собой функцию, которая отображает каждый элемент в пространстве выборки на линию действительных чисел.
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Преобразование случайных величин ― пусть переменные X и Y связаны некоторой функцией. Обозначим fX и fY функцию распределения X и Y соответственно у нас есть:
```suggestion
&#10230; Преобразование случайных величин ― пусть переменные X и Y связаны некоторой функцией. Обозначим fX и fY функциями распределения X и Y соответственно, тогда у нас есть:
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Распределения вероятностей
```suggestion
&#10230; Вероятностные распределения
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Совместно распределенные случайные переменные
```suggestion
&#10230; Совместно распределенные случайные величины
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Корреляция ― Обозначим σX,σY стандартных отклонений X и Y, мы определяем корреляцию между случайными величинами X и Y, отмеченными ρXY, следующим образом:
```suggestion
&#10230; Корреляция ― Обозначим σX,σY стандартные отклонения X и Y, мы определяем корреляцию между случайными величинами X и Y, обозначенную как ρXY, следующим образом:
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Примечание: выборочное среднее несмещенное, т. е E[¯¯¯¯¯X]=μ.
```suggestion
&#10230; Примечание: выборочное среднее является несмещенным, т. е E[¯¯¯¯¯X]=μ.
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Выборочная дисперсия ― Дисперсия случайной выборки используется для оценки истинной дисперсии σ2 распределения, часто обозначается как s2 или ^σ2 и определяется следующим образом:
```suggestion
&#10230; Дисперсия выборки ― Дисперсия случайной выборки используется для оценки истинной дисперсии σ2 распределения, часто обозначается как s2 или ^σ2 и определяется следующим образом:
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Примечание: дисперсия выборки несмещенная, то есть E[s2]=σ2.
```suggestion
&#10230; Примечание: дисперсия выборки является несмещенной, то есть E[s2]=σ2.
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Отношение хи-квадрат с дисперсией выборки ― пусть s2 будет дисперсией выборки случайной выборки. У нас есть:
```suggestion
&#10230; Отношение между распределением хи-квадрат и дисперсией выборки ― пусть s2 будет дисперсией выборки случайной выборки. У нас есть:
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/shervinea
```suggestion
&#10230; Авторы оригинала: Afshine Amidi и Shervine Amidi ― https://github.com/afshinea и https://github.com/shervinea
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Российская адаптация: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```suggestion
&#10230; Переведено на русский язык: Пархоменко Александр ― https://github.com/AlexandrParkhomenko
```

2021-02-17 15:30 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Проверено X, Y и Z
```suggestion
&#10230; Проверено на русском языке: Труш Георгий (Georgy Trush) ― https://github.com/geotrush
```

2021-02-17 15:46 UTC, AlexandrParkhomenko commented on ru/cs-229-probability.md
> +&#10230; Введение в вероятность и комбинаторику
где-то видел Теория <s>вероятности</s> веоятностей

2021-02-17 15:51 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Введение в вероятность и комбинаторику
@AlexandrParkhomenko Я "Теория Вероятности" видел на двух учебниках и в названии курса в универе, думаю, что это корректно.

2021-02-17 15:52 UTC, AlexandrParkhomenko commented on ru/cs-229-probability.md
> +&#10230; Комбинация ― Combination - это расположение r объектов из пула, состоящего из n объектов, где порядок не имеет значения. Количество таких расположений дается C(n,r), определяемым как:
шутка: Нормальный корень пул, даже аэропорт есть Пулково.

2021-02-17 16:06 UTC, AlexandrParkhomenko commented on ru/cs-229-probability.md
> +&#10230; Примечание: выборочное среднее несмещенное, т. е E[¯¯¯¯¯X]=μ.
Как с формулами будут разбираться, ума не приложу.  $E[\overline{X}]=\mu$

или A Algorithm A with star

2021-02-17 16:15 UTC, AlexandrParkhomenko commented on ru/cs-229-probability.md
> +&#10230; Введение в вероятность и комбинаторику
Точно. Помню строили график распределения с  одногруппниками "волна пошла" пока лектор на доске писал формулы, тогда была вроде Теория вероятности

2021-02-19 10:43 UTC, geotrush requested changes
The previous translation was correct, my bad 😑

2021-02-19 10:43 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Памятка: Теория Вероятности и Статистика
```suggestion
&#10230; Памятка: Теория Вероятностей и Статистика
```

2021-02-19 10:43 UTC, geotrush commented on ru/cs-229-probability.md
> +&#10230; Введение в Теорию Вероятности и Комбинаторику
```suggestion
&#10230; Введение в Теорию Вероятностей и Комбинаторику
```

2021-02-19 10:58 UTC, AlexandrParkhomenko commented on ru/cs-229-probability.md
> +&#10230; Введение в Теорию Вероятности и Комбинаторику
Поправил веб.

2022-08-18 17:52 UTC, closed without merging