[ru] cs-230-convolutional-neural-networks
shervinea/cheatsheet-translation pull request #227
Opened 2020-12-23 11:17 UTC by AlexandrParkhomenko

2021-02-15 16:01 UTC, geotrush requested changes
Superb translation! I'm proposing some minor typo fixes.

2021-02-15 16:01 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Проверено X, Y и Z
```suggestion
&#10230; Проверено на русском языке: Труш Георгий (Georgy Trush) ― https://github.com/geotrush
```

2021-02-15 16:15 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Потеря триплета ― Triplet loss ℓ - это функция потерь, вычисленная на представлении триплета изображений A (anchor), P (positive) и N (negative). Якорь (anchor) и положительный пример относя
```suggestion
&#10230; Потеря тройки ― Triplet loss ℓ - это функция потерь, вычисленная на представлении тройки изображений A (anchor), P (positive) и N (negative). Якорь (anchor) и положительный пример относятся к одному классу, а отрицательный пример - к другому. Называя α∈R+ параметром отступа, этот потеря определяется следующим образом:
```

2021-02-15 16:16 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Обучение одним выстрелом ― One Shot Learning - это алгоритм проверки лица, который использует ограниченный обучающий набор для изучения функции сходства, которая количественно определяет, на
```suggestion
&#10230; Обучение с первого раза ― One Shot Learning - это алгоритм проверки лица, который использует ограниченный обучающий набор для изучения функции сходства, которая количественно определяет, насколько разные два заданных изображения. Функция подобия, применяемая к двум изображениям, часто обозначается d(image 1,image 2).
```

2021-02-15 16:17 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Передача нейронного стиля
```suggestion
&#10230; Нейронный перенос стиля
```

2021-02-15 16:20 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Обнаружение объектов, Типы моделей, Обнаружение, Пересечение по объединению, Подавление немаксимума, YOLO, R-CNN]
&#10230; [Обнаружение объектов, Типы моделей, Обнаружение, Пересечение по объединению, Подавление не-максимумов, YOLO, R-CNN]

2021-02-15 16:22 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Проверка/распознавание лиц, Обучение одним выстрелом, Сиамская сеть, Triplet loss]
```suggestion
&#10230; [Проверка/распознавание лиц, Обучение с одного раза, Сиамская сеть, Triplet loss]
```

2021-02-15 16:24 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Перенос нейронного стиля, Активация, Матрица стилей, Функция стоимости стиля/контента]
```suggestion
&#10230; [Нейронный перенос стиля, Активация, Матрица стиля, Функция стоимости стиля/контента]
```

2021-02-15 16:28 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Max-пулинг, Усредненный пулинг, Каждая операция пулинга выбирает максимальное значение текущего просмотра, Каждая операция пулинга усредняет значения текущего представления]
```suggestion
&#10230; [Max-пулинг, Усредненный пулинг, Каждая операция пулинга выбирает максимальное значение текущего представления, Каждая операция пулинга усредняет значения текущего представления]
```

2021-02-15 16:31 UTC, AlexandrParkhomenko commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Архитектуры вычислительных трюков, Generative Adversarial Net, ResNet, Inception Network]
Спасибо за рецензии. Это элемент меню. Лучше сделать короче, чем длиннее.

2021-02-15 16:31 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Сохраняет обнаруженные функции, Наиболее часто используемые, Карта функций уменьшенных образцов, Используется в LeNet]
```suggestion
&#10230; [Сохраняет обнаруженные функции, Наиболее часто используется, Уменьшает размерность карты признаков, Используется в LeNet]
```

2021-02-15 16:33 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Архитектуры вычислительных трюков, Generative Adversarial Net, ResNet, Inception Network]
Хорошо, исправил.

2021-02-15 16:40 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Слой Пулинга ― Pooling (POOL) - это операция понижающей дискретизации, обычно применяемая после сверточного слоя, который обеспечивает некоторую пространственную инвариантность. В частности,
```suggestion
&#10230; Слой Пулинга ― Pooling (POOL) - это операция понижающей дискретизации, обычно применяемая после сверточного слоя, который обеспечивает пространственную инвариантность изображенных объектов. В частности, max-пулинг и усредненный пулинг - это особые виды пулинга, в которых берется максимальное и среднее значение соответственно.
```

2021-02-15 16:41 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Размеры фильтра ― Фильтр размера F×F, применяемый к входу, содержащему каналы C, представляет собой объём F×F×C, который выполняет свертки на входе размера I×I×C и создает карту выходных хар
```suggestion
&#10230; Размеры фильтра ― Фильтр размера F×F, применяемый к входу, содержащему каналы C, представляет собой объём F×F×C, который выполняет свертки на входе размера I×I×C и создает карту выходных признаков (также называемую картой активации) размера O×O×1.
```

2021-02-15 16:43 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Без дополнения, Отбрасывает последнюю свертку при несовпадении размеров, Дополнения для карты объектов с размерами ⌈IS⌉, Размер вывода математически удобен, Также называется 'половинным' до
```suggestion
&#10230; [Без дополнения, Отбрасывает последнюю свертку при несовпадении размеров, Дополнения для карты признаков с размерами ⌈IS⌉, Размер вывода математически удобен, Также называется 'половинным' дополнением, Максимальное дополнение. С ним концевые свертки применяются к границам входа, Фильтр 'видит' вход от начала до конца]
```

2021-02-15 16:45 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Ввод сглаживается, Один параметр смещения на нейрон, Количество нейронов FC не имеет структурных ограничений]
```suggestion
&#10230; [Вход сглаживается, Один параметр смещения на нейрон, Количество нейронов FC не имеет структурных ограничений]
```

2021-02-15 16:47 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Сложности нелинейности поддаются биологической интерпретации, Решает проблему умирания ReLU для отрицательных значений, Дифференцируема везде]
```suggestion
&#10230; [Сложности нелинейности поддаются биологической интерпретации, Решает проблему зануления ReLU отрицательных значений, Дифференцируема везде]
```

2021-02-15 16:50 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Softmax ― Шаг softmax можно рассматривать как обобщенную логистическую функцию, которая принимает на вход вектор оценок x∈Rn и выводит вектор выходной вероятности p∈Rn через функцию softmax
```suggestion
&#10230; Softmax ― Шаг softmax можно рассматривать как обобщенную логистическую функцию, которая принимает на вход вектор оценок x∈Rn и выводит вектор вероятностей классов p∈Rn через функцию softmax в конце архитектуры. Это определяется следующим образом:
```

2021-02-15 16:53 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Оригинальное изображение, Деление на сетку GxG, Предсказание ограничивающей рамки, Подавление немаксимальных]
```suggestion
&#10230; [Оригинальное изображение, Деление на сетку GxG, Предсказание ограничивающей рамки, Подавление немаксимумов]
```

2021-02-15 16:54 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Оригинальное изображение, Сегментация, Прогнозирование ограничивающей рамки, Подавление немаксимальных]
```suggestion
&#10230; [Оригинальное изображение, Сегментация, Прогнозирование ограничивающей рамки, Подавление немаксимумов]
```

2021-02-15 16:56 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Это правильный человек?, Один-к-одному поиск, Это одно из K лиц в базе данных?, Один-к-многим поиск]
```suggestion
&#10230; [Это правильный человек?, Поиск one-to-one, Это одно из K лиц в базе данных?, Поиск one-to-many]
```

2021-02-15 16:57 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Мотивация ― цель переноса нейронного стиля - создать изображение G на основе заданного контента C и заданного стиля S.
```suggestion
&#10230; Мотивация ― цель нейронного переноса стиля - создать изображение G на основе заданного контента C и заданного стиля S.
```

2021-02-15 16:58 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Матрица стиля ― Матрица стилей G[l] данного слоя l является определителем Грама, где каждый из его элементов G[l]kk′ количественно определяет степень корреляции каналов k и k′. Она определяе
```suggestion
&#10230; Матрица стиля ― Матрица стиля G[l] данного слоя l является определителем Грама, где каждый из его элементов G[l]kk′ количественно определяет степень корреляции каналов k и k′. Она определяется по отношению к активациям a[l] следующим образом:
```

2021-02-15 17:05 UTC, AlexandrParkhomenko commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Передача нейронного стиля
В web-версии было исправлено. Это работа российских ребят, тут других вариантов нет.

2021-02-15 17:12 UTC, AlexandrParkhomenko commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Сохраняет обнаруженные функции, Наиболее часто используемые, Карта функций уменьшенных образцов, Используется в LeNet]
Запятые здесь - разделители не связанных выражений. Не пофиксили https://github.com/shervinea/cheatsheet-translation/issues/230

2021-02-15 17:14 UTC, AlexandrParkhomenko commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Сохраняет обнаруженные функции, Наиболее часто используемые, Карта функций уменьшенных образцов, Используется в LeNet]
Там что-то в таком виде: Карта признаков даунсэмплов

2021-02-15 17:17 UTC, AlexandrParkhomenko commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Слой Пулинга ― Pooling (POOL) - это операция понижающей дискретизации, обычно применяемая после сверточного слоя, который обеспечивает некоторую пространственную инвариантность. В частности,
Повороты не сильно, перенос немного?

2021-02-15 17:20 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Сохраняет обнаруженные функции, Наиболее часто используемые, Карта функций уменьшенных образцов, Используется в LeNet]
В оригинале вообще "Downsamples feature map" и это стоит переводить как "Уменьшает размерность карты признаков"

2021-02-15 17:24 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Слой Пулинга ― Pooling (POOL) - это операция понижающей дискретизации, обычно применяемая после сверточного слоя, который обеспечивает некоторую пространственную инвариантность. В частности,
Можно добиться полноценной пространственной инвариантности, используя повороты на совершенно разные углы и переносы в различные части изображения даже с довольно сильным выходом за границы, а также другие augmentations.

2021-02-15 17:28 UTC, AlexandrParkhomenko commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Softmax ― Шаг softmax можно рассматривать как обобщенную логистическую функцию, которая принимает на вход вектор оценок x∈Rn и выводит вектор выходной вероятности p∈Rn через функцию softmax
Это же просто нормировка вероятности. 

> Функция softmax чаще всего используется как выход классификатора для представления распределения вероятности n классов. Реже функция softmax используется внутри самой модели, когда мы хотим, чтобы модель выбрала один из n вариантов какой-то внутренней переменной.

2021-02-15 17:33 UTC, geotrush commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; Softmax ― Шаг softmax можно рассматривать как обобщенную логистическую функцию, которая принимает на вход вектор оценок x∈Rn и выводит вектор выходной вероятности p∈Rn через функцию softmax
Это "нормировка" выходных значений нейронной сети, которые ещё называют логитами (logits). Результатом "нормировки" логитов софтмаксом является вектор вероятностей классов.

2021-02-17 17:26 UTC, AlexandrParkhomenko commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Сохраняет обнаруженные функции, Наиболее часто используемые, Карта функций уменьшенных образцов, Используется в LeNet]
Спасибо, исправил.

2021-02-17 17:57 UTC, AlexandrParkhomenko commented on ru/cs-230-convolutional-neural-networks.md
> +&#10230; [Обучение, Шум, Реальное изображение, Генератор, Дискриминатор, Настоящее Подделка]
Подпись на изображении.

2022-08-18 17:52 UTC, closed without merging