[ru] cs-230-recurrent-neural-networks
shervinea/cheatsheet-translation pull request #229
Opened 2020-12-23 11:47 UTC by AlexandrParkhomenko

`1. Split the current pull request into the following ones ...`
done ✓
`2. Invite anyone you would know to review your work in these each of these pull requests.`
Now the winter session begins, maybe the teachers of the @esokolov level will be able to find time.
Please make articles in the form in which people can read them - **pdf** or **html**.

2020-12-24 21:29 UTC, shervinea commented
Thank you @AlexandrParkhomenko for all your time in submitting these PRs! This looks great. Thanks for inviting other people you know for the reviews. Looking forward to it!

Once these changes are reviewed and approved, we'll take care of the conversion to the appropriate web/PDF format.

2020-12-27 13:45 UTC, AlexandrParkhomenko commented
web format: [Recurrent Neural Networks](https://alexandrparkhomenko.github.io/stanford/cs-230/recurrent-neural-networks/index.html)

2021-02-15 19:00 UTC, tensorush requested changes
Great job! I'm suggesting some improvements.

2021-02-16 13:51 UTC, AlexandrParkhomenko commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; [Обзор, Структура архитектуры, Приложения RNN, Функция потерь, Обратное распространение]
Поменял на четырёх интернет страничках.

2021-02-16 13:53 UTC, geotrush commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; [Обзор, Структура архитектуры, Приложения RNN, Функция потерь, Обратное распространение]
Супер 👍🏼

2021-02-16 14:21 UTC, AlexandrParkhomenko commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; [Традиционная нейронная сеть, Генерация музыки, Классификация эмоций (Sentiment classification), Распознавание именованных сущностей (Name entity recognition NER), Машинный перевод]
Места хватит всем. Традиционная - это школа Andrew Ng.

2021-02-16 14:28 UTC, AlexandrParkhomenko commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; Исчезающий/взрывающийся градиент ― Явления исчезающих и взрывных градиентов часто встречаются в контексте RNN. Причина, по которой они происходят, заключается в том, что трудно зафиксировать
> Когда говорят о проблеме исчезающего и взрывного градиента, имеют в виду, что в результате вычислений с таким графом градиенты также умножаются на коэффициент diag(λ) t .

2021-02-16 14:33 UTC, geotrush commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; Исчезающий/взрывающийся градиент ― Явления исчезающих и взрывных градиентов часто встречаются в контексте RNN. Причина, по которой они происходят, заключается в том, что трудно зафиксировать
Это уже просто синтаксическая ошибка, которая начала закрепляться в русском переводе. Корректнее написать взрывающихся, так же, как и исчезающий -- это видно и из английского варианта. Взрывной был бы, если было explosive, вместо exploding.

2021-02-16 14:40 UTC, AlexandrParkhomenko commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; [1-hot представление, Представления слов]
А тут усложняете простую идею.

2021-02-16 14:45 UTC, AlexandrParkhomenko commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; Изучение представления слов
Может представление обучающих слов?

2021-02-16 14:45 UTC, geotrush commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; [1-hot представление, Представления слов]
Не принято писать этот термин через число. Можно, но чаще используется one-hot.

2021-02-16 14:49 UTC, geotrush commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; Изучение представления слов
Нет, имеется в виду, обучение моделей формировать представления слов. Кстати, такой вопрос, вы все мои ответы на ваши комментарии видите? И приходят ли вам уведомления, как и мне?

2021-02-16 15:34 UTC, AlexandrParkhomenko commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; [Читает милый плюшевый мишка, плюшевый мишка, мягкий, персидская поэзия, искусство]
![](https://alexandrparkhomenko.github.io/stanford/cs-230/recurrent-neural-networks/attention-model-captioning-1-en.jpeg)
![](https://alexandrparkhomenko.github.io/stanford/cs-230/recurrent-neural-networks/attention-model-captioning-1-en.jpeg)

2021-02-16 15:38 UTC, AlexandrParkhomenko commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; [Обучить сеть на прокси-задаче, Извлечь высокоуровневое представление, Вычислить представления слов]
Этого почему-то нет в тексте.

2021-02-16 15:43 UTC, AlexandrParkhomenko commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; Skip-gram ― Модель word2vec с пропуском граммы - это задача с контролем учителем, которая изучает встраивание слов, оценивая правдоподобие того, что любое заданное целевое слово t встречаетс
Я не уверен, что ребята смогут найти все перестановки формул. 

---------------------------------------------------------------------------------------------
I'm not sure the guys can find all the rearrangements of formulas.

2021-02-16 16:00 UTC, AlexandrParkhomenko commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; Ширина луча ― Ширина луча B является параметром лучевого поиска. Большие значения B дают лучший результат, но с меньшей производительностью и увеличенным объёмом памяти. Маленькие значения B
computationally intensive != качество

2021-02-16 16:01 UTC, AlexandrParkhomenko commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; Обзор ― модель машинного перевода похожа на языковую модель, за исключением того, что в ней размещена сеть кодировщика. По этой причине её иногда называют моделью условного языка. Цель состо
получаем условный язык

2021-02-16 16:04 UTC, geotrush commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; Обзор ― модель машинного перевода похожа на языковую модель, за исключением того, что в ней размещена сеть кодировщика. По этой причине её иногда называют моделью условного языка. Цель состо
Какой условный язык? Модель авторегрессионная вычисляет условную вероятность следующих слов.

2021-02-16 19:29 UTC, AlexandrParkhomenko commented on ru/cs-230-recurrent-neural-networks.md
> +&#10230; Изучение представления слов
Проще на гите прочитать. На почту неформатированным пакетом приходит.

2022-08-18 17:52 UTC, closed without merging